package com.dm.adf.common.baseapp.testmodel.test.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 09 21:28:59 PST 2017
// ---------------------------------------------------------------------
public interface PrgHRService extends ApplicationModule {
    void test();
}
