package com.dm.adf.common.baseapp.testmodel.test.service.client;


import com.dm.adf.common.baseapp.testmodel.test.service.common.PrgHRService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 09 21:28:59 PST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrgHRServiceClient extends ApplicationModuleImpl implements PrgHRService {
    /**
     * This is the default constructor (do not remove).
     */
    public PrgHRServiceClient() {
    }

    public void test() {
        Object _ret = this.riInvokeExportedMethod(this, "test", null, null);
        return;
    }
}
