package com.dm.adf.common.baseapp.testmodel.test.vo;

import com.dm.adf.common.baseapp.basemodel.framework.extension.view.prg.GenericDataReadServiceInterface;
import com.dm.adf.common.baseapp.basemodel.framework.extension.view.prg.PrgViewObjectImpl;
import com.dm.adf.common.baseapp.testmodel.test.MyEmpDataServiceImplementation;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 12 16:46:01 PST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PGEmployeeVOImpl extends PrgViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PGEmployeeVOImpl() {
    }

    public GenericDataReadServiceInterface getService() {
        return MyEmpDataServiceImplementation.getInstance();
    }
}
