package com.dm.adf.common.baseapp.testmodel.test.eo;


import com.dm.adf.common.baseapp.basemodel.framework.extension.entity.prg.GenericDataPersistanceService;
import com.dm.adf.common.baseapp.basemodel.framework.extension.entity.prg.PrgEntityObjectImpl;
import com.dm.adf.common.baseapp.testmodel.test.MyEmpDataServiceImplementation;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 12 16:35:30 PST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PGEmployeeEOImpl extends PrgEntityObjectImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * This is the default constructor (do not remove).
     */
    public PGEmployeeEOImpl() {
    }

    /**
     * @param employeeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long employeeId) {
        return new Key(new Object[]{employeeId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.dm.adf.common.baseapp.testmodel.test.eo.PGEmployeeEO");
        }
        return mDefinitionObject;
    }


    public GenericDataPersistanceService getService() {
        return MyEmpDataServiceImplementation.getInstance();
    }
}
